version: '3'

services:
  db:
    image: postgres:13
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: moodtracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "moodtracker"]
      interval: 10s   # Check every 10 seconds
      retries: 5      # Retry 5 times before marking the container as unhealthy
      start_period: 30s  # Wait 30 seconds before starting health checks
      timeout: 5s      # Timeout after 5 seconds if the check fails
    networks:
      - moodtracker_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - moodtracker_network

networks:
  moodtracker_network:
    driver: bridge

# volumes:
#   postgres_data:
